add first changes in shared UI components
Tranzitivnost/movies-catalog pull request #2
Opened 2024-12-06 15:54 UTC by Tranzitivnost

2024-12-21 14:05 UTC, sergeyteleshev requested changes

2024-12-21 14:05 UTC, sergeyteleshev commented on src/entities/movies/ui/SummaryGeneralMovie.tsx
why empty files?

2024-12-21 14:05 UTC, sergeyteleshev commented on src/entities/movies/ui/GeneralMoviePreview.tsx
> +      <img className={styles.img} src={movie.backdrop_path} alt={movie.title} />
`Image` - use this component instead in all places you have `img` tag

2024-12-21 14:05 UTC, sergeyteleshev commented on src/features/popular-movies/ui/PopularMoviesPreview.tsx
> +      <Container flexWrap justifyBetween gap="16px">
![Снимок экрана 2024-12-21 в 15 05 21](https://github.com/user-attachments/assets/8b7de54e-3d78-4ba4-b9c1-2b31c99caa1d)

2024-12-26 18:06 UTC, Tranzitivnost commented on src/features/popular-movies/ui/Footer.tsx
> +export function Footer() {
*

2024-12-26 18:20 UTC, Tranzitivnost commented on src/features/popular-movies/ui/PopularMoviesPreview.tsx
> +      <Container flexWrap justifyBetween gap="16px">
I fixed that. But I thought we were gonna do a slider in this place.

2024-12-26 18:21 UTC, Tranzitivnost commented on src/features/popular-movies/ui/PosterMovie.tsx
> +export function PosterMovie({ children, className }: Props) {
*

2024-12-26 18:21 UTC, Tranzitivnost commented on src/pages/home/ui/HomePage.tsx
> +        <SummaryMovie movie={popularMovies[0]} key={popularMovies[0].id} />
*

2024-12-26 18:26 UTC, Tranzitivnost commented on src/shared/ui/components/Container.tsx
> +  children?: React.ReactNode
I don't sure. Because I did "gradient" with just empty Container.

2024-12-26 18:28 UTC, Tranzitivnost commented on src/shared/ui/components/Link.tsx
> +  href?: string
*

2024-12-26 20:57 UTC, Tranzitivnost commented on src/features/popular-movies/ui/Footer.module.css
> +  font-family: Rubik;
*

2024-12-26 20:58 UTC, Tranzitivnost commented on src/app/layout/App.tsx
> +      </Container>
*

2025-01-12 20:51 UTC, sergeyteleshev commented on src/widgets/popular-movies/ui/PopularMoviesPreview.tsx
> +  const { popularMovies } = usePopularMovies({ page: 1 })
you load this movies already in the parent component. you can pass movies via props or get it from redux store

2025-01-13 22:49 UTC, sergeyteleshev requested changes

2025-01-13 22:49 UTC, sergeyteleshev commented on src/features/poster-movie/ui/PosterMovie.tsx
> +  const { popularMovies } = usePopularMovies({ page: 1 })
basically `popularMovies` and `movies` from props is the same movies. no need to duplicate it

2025-01-13 22:49 UTC, sergeyteleshev commented on src/features/poster-movie/ui/PosterMovie.tsx
> +      )}
this is pretty small component. you decomposed it too early and placed somewhere far from this component. lets keep all together here. so just move layout with styles from components to here

2025-01-13 22:49 UTC, sergeyteleshev commented on src/features/poster-movie/ui/PosterMovie.tsx
> +        {children}
unused

2025-01-13 22:49 UTC, sergeyteleshev commented on src/features/poster-movie/ui/PosterMovie.tsx
> +export function PosterMovie({ children, movies, className }: Props) {
Seems like PosterMovie is gonna be reused in next PR. so please keep that in mind (need to place it somewhere different spot and do something with props)

2025-01-13 22:49 UTC, sergeyteleshev commented on src/widgets/page/ui/page-header/PageHeader.module.css
> +  position: absolute;
lets make it as additional prop to the component. so header can positioned as usual (no changes) and with `absolute` positioning

2025-01-15 22:14 UTC, sergeyteleshev requested changes

2025-01-15 22:14 UTC, sergeyteleshev commented on src/widgets/page/ui/page-footer/PageFooter.module.css
> +  flex-direction: column;
use component use props

2025-01-15 22:14 UTC, sergeyteleshev commented on src/widgets/page/ui/page-footer/PageFooter.module.css
> +  width: 444px;
it is supposed to be length of the page

2025-01-17 21:21 UTC, Tranzitivnost commented on src/shared/ui/components/Link.tsx
> +  children?: React.ReactNode
I did it for convenience

2025-01-18 17:44 UTC, sergeyteleshev requested changes

2025-01-18 17:44 UTC, sergeyteleshev commented on src/entities/movies/ui/MoviePreview.tsx
> +      </Container>
do you think we can avoid this container? and may be just use image + css for the same layout effect you need?

2025-01-18 17:44 UTC, sergeyteleshev commented on src/features/movies-list/ui/MoviesList.module.css
> +  /* I don't know if this style is necessary. */
please, figure it out wether you need it or not. lets keep code clean always

2025-01-18 17:44 UTC, sergeyteleshev commented on src/features/movies-list/ui/MoviesList.tsx
> +          : "No available films"}
you can wrap it with your `<Text>` component

2025-01-18 17:44 UTC, sergeyteleshev commented on src/features/poster-movie/ui/PosterMovie.module.css
> +}
seems like we did not do `css reset`
please, see the previous project we did and apply this to current project so you don't need to do hacks like this

2025-01-18 17:44 UTC, sergeyteleshev commented on src/features/poster-movie/ui/PosterMovie.module.css
> +  height: 648px;
`height: 100%`?
you just did the sizing in the parent container

2025-01-18 17:44 UTC, sergeyteleshev commented on src/features/poster-movie/ui/PosterMovie.module.css
> +  /* margin: 0px 242px 0px 242px; */
please remove all unused lines of code everywhere

2025-01-18 17:44 UTC, sergeyteleshev commented on src/features/poster-movie/ui/PosterMovie.tsx
> +    .map((sentence, index) => <p key={index}>{sentence}</p>)
let implement together a better algorithm here in order to handle cases with other punctuation signs (single and multiple ones)

2025-01-18 17:44 UTC, sergeyteleshev commented on src/pages/home/ui/HomePage.tsx
> +      <PageHeader position="absolute" />
this prop looks weird
we use props like in `Container` component as booleans. so lets treat this one similar more obvious way. cause someone can make a mistake and write something like `"absalute"` and this code wont work

like this:
`<PageHeader positionAbsolute />`

2025-01-18 17:44 UTC, sergeyteleshev commented on src/pages/home/ui/HomePage.module.css
> +  /* width: 1650px; */
this one is correct. why did you comment it?

2025-01-18 17:44 UTC, sergeyteleshev commented on src/shared/ui/components/AddWatchListButton.module.css
> +  align-items: center;
you could've just simply written `textAlign: center`

2025-01-18 17:44 UTC, sergeyteleshev commented on src/shared/ui/components/AddWatchListButton.module.css
> +  text-align: left;
and remove this one

2025-01-18 17:44 UTC, sergeyteleshev commented on src/shared/ui/components/AddWatchListButton.module.css
> +  gap: 10;
this one is not working. it is supposed tome 10 of something: `px, %, pt, etc.`

2025-01-18 17:44 UTC, sergeyteleshev commented on src/shared/ui/components/LikeButton.module.css
> +  gap: 10;
same

2025-01-18 17:44 UTC, sergeyteleshev commented on src/shared/ui/components/Link.tsx
> +  children?: React.ReactNode
sorry, i dont what you mean. in each place you used it you have a children. the link is always applies to something: text, image, components

2025-01-18 17:44 UTC, sergeyteleshev commented on src/shared/ui/styles/mixins-theme.scss
> +  // }
we'll define style system in the next PR. lets delete that for now

2025-02-08 21:32 UTC, sergeyteleshev requested changes

2025-02-08 21:32 UTC, sergeyteleshev commented on src/features/poster-movie/ui/PosterMovie.tsx
> +    ?.match(/[^.!?]+[.!?]+|\w+$/g)
you dont need `?` cause overview is always a string

2025-02-08 21:32 UTC, sergeyteleshev commented on src/features/poster-movie/ui/PosterMovie.tsx
> +        </Container>
i dont think you need a container with only one element. you can just apply styles from container to your image and thats it

2025-02-08 21:32 UTC, sergeyteleshev commented on src/widgets/page/ui/page-header/PageHeader.module.css
> +  height: 19px;
fixed height is a bad practice for containers

2025-02-12 21:27 UTC, sergeyteleshev approved these changes

2025-02-12 21:27 UTC, sergeyteleshev commented on src/app/layout/reset-styles.css
>  code {
you dont need this style

2025-02-12 21:27 UTC, sergeyteleshev approved these changes

2025-02-12 21:29 UTC, merged